{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kube-prometheus-stack.namespace" . }}
  labels:
    {{- include "kube-prometheus-stack.labels" . | nindent 4 }}
    kubernetes.io/metadata.name: {{ include "kube-prometheus-stack.namespace" . }}
  {{- with .Values.namespaceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
